### ISSUE TITLE
nRF52840-DK not recognized

### ISSUE THREAD

**Issue by DangZRQ** [NordicSemiconductor/nRF-Sniffer-for-802.15.4#33]
Hello!
nRF52840-DK[v0.9.3] cannot be recognized when connecting to J3 nRF USB port.
So I can't start sniffing even if I finish flashing firmware.

**Comment by e-rk** [comment]
nRF52840 Engineering A chip support is end of life. Nordic has supported this Engineering version of silicon up to, and beyond, the previously communicated period, to support prototype builds with nRF52840. In [this section](https://infocenter.nordicsemi.com/index.jsp?topic=%2Fcomp_matrix_nrf52840%2FCOMP%2Fnrf52840%2FnRF52840_ic_rev_comp_with_dev_hw.html) you can find compatibility matrix between the nRF52840 IC revisions and development kits.
