### ISSUE TITLE
Segfault on capture start Wireshark 3.2.0

### ISSUE THREAD

**Issue by Beetix** [NordicSemiconductor/nRF-Sniffer-for-802.15.4#40]
Hi,

I am getting a segfault when starting a capture on Wireshark 3.2.0 (tested on Linux and Windows).

Does anyone have an idea on why it crashes?

Thanks

**Comment by stig-bjorlykke** [comment]
Hi.

I think this is related to [Wireshark bug 16311](https://bugs.wireshark.org/bugzilla/show_bug.cgi?id=16311). Try using version 3.0.7 or wait for version 3.2.1 which will be released next week. Or, if you want to help testing, you can try downloading latest 3.2.1rc0 [daily build](https://www.wireshark.org/download/automated/).

**Comment by Beetix** [comment]
Thanks! I've built 3.2.1rc0 in Linux and successfully started the capture.
