### ISSUE TITLE
sniffer not support xiaomi phone's BLE packet

### ISSUE THREAD

**Issue by fr0zenrain** [NordicSemiconductor/nRF-Sniffer-for-802.15.4#49]
my device is nRF52840, i can't capture Xiaomi phone's BLE packet.

**Comment by e-rk** [comment]
This sniffer firmware can capture only IEEE 802.15.4 packets and is unable to display BLE traffic.
For BLE use this one instead: https://www.nordicsemi.com/Software-and-tools/Development-Tools/nRF-Sniffer-for-Bluetooth-LE
