### ISSUE TITLE
Implausible RSS values

### ISSUE THREAD

**Issue by ribsey** [NordicSemiconductor/nRF-Sniffer-for-802.15.4#67]
The currently available firmware (at least for the dongle) measures unplausible RSSI values.
As seen in the screenshot, the values are out of normal range and sometimes even positive.
![2024-06-06_14h09_37](https://github.com/NordicSemiconductor/nRF-Sniffer-for-802.15.4/assets/25552310/a3f4bbb9-f9d2-4c73-825d-81611a104552)
When using the [Release v0.7.2](https://github.com/NordicSemiconductor/nRF-Sniffer-for-802.15.4/releases/tag/v0.7.2) the values seem plausible

**Comment by e-rk** [comment]
Fixed in https://github.com/NordicSemiconductor/nRF-Sniffer-for-802.15.4/pull/69
